In [1]:
import torch
from custom_transformer import CustomTransformer

In [2]:
torch.manual_seed(1234)

In [3]:
# Testing on random input text before actual python scripts to make sure everything works.
with (open("../data/input.txt", "r") as file):
    text = file.read()

vocab = sorted(set(text))
print(len(vocab))

65


In [4]:
ctoi = {ch : i for i, ch in enumerate(vocab)}
itos = {i : ch for i, ch in enumerate(vocab)}

encode = lambda s : [ctoi[c] for c in s]
decode = lambda s : ''.join([itos[i] for i in s])

In [5]:
data = encode(text)
train_size = int(len(data) * .9)
train = data[:train_size]
test = data[train_size:]

def get_batches(dataset, batches, context_len):
    pos = torch.randint(len(dataset) - context_len, (batches,))
    x = torch.stack([torch.tensor(dataset[x : x + context_len]) for x in pos])
    y = torch.stack([torch.tensor(dataset[x + 1 : x + context_len + 1]) for x in pos])

    return x,y

In [6]:
transformer = CustomTransformer(len(vocab), 10, 20, 4, 2)
optimizer = torch.optim.Adam(transformer.parameters(), lr=1e-3)

In [8]:
for i in range(10):
    train_in, train_target = get_batches(train, 4, 10)

    logits, loss = transformer(train_in, train_target)
    optimizer.zero_grad(set_to_none=True)
    loss.backward()
    optimizer.step()
    
    print(loss.item())

torch.Size([40])
torch.Size([40, 65])
tensor([52,  1, 46, 43, 39, 56,  8,  1, 15, 53, 56, 49,  1, 53, 56,  1, 61, 47,
        50, 58, 53, 52,  1, 58, 46, 43,  1, 43, 39, 56,  6,  1, 51, 63,  1, 50,
        53, 53, 49, 57])
4.170228481292725
torch.Size([40])
torch.Size([40, 65])
tensor([57,  1, 50, 47, 43, 44,  1, 40, 43,  1, 59, 52, 58, 39, 59, 45, 46, 58,
         1, 50, 43, 56, 10,  1, 47, 44,  0, 63, 53, 59, 61, 52,  8,  1, 15, 39,
        50, 50,  1, 63])
4.129917621612549
torch.Size([40])
torch.Size([40, 65])
tensor([57,  1, 61, 47, 58, 46,  1, 46, 53, 50,  0, 19, 24, 27, 33, 15, 17, 31,
        32, 17, 43, 42,  6,  0, 26, 53,  1, 56, 47, 41, 56, 43,  1, 51, 39, 49,
        43, 57,  1, 58])
4.118072986602783
torch.Size([40])
torch.Size([40, 65])
tensor([39, 57,  1, 58, 46, 53, 59,  1, 50, 53, 58, 47, 53, 52,  1, 53, 44,  1,
        54, 53,  1, 58, 53,  1, 46, 53, 50, 42,  1, 51, 39, 50, 50, 57,  2,  0,
        30, 53, 59, 45])
3.81141996383667
torch.Size([40])
torch.Size([40, 65])